<a href="https://colab.research.google.com/github/CE605A/Anukul-Dwivedi_231030402/blob/main/CE605A_231030402.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing numpy to use the function of numpy in my entire program
from numpy import*
#Question 1
print('Manual Input:')
#Manually
#Row Vector
print('Row Vector:')
m= matrix('1 2 3')
print(m)
#Column Vector
print('Column Vector:')
n=matrix('1; 2; 3')
print(n)

print('Input Method:')
#Input Method
import numpy as np #Importing numpy to use numpy operations
#For Row Vector
print('Row Vector:')
#Asking user to input number of column he/she want
C= int(input('Enter number of column:'))
m= []
#Iterating the loop for size of column
for j in range(C):
  #Asking user to input the elements of matrix
  a=int(input('Enter elements of Vector:'))
  m.append(a) #To add each elements in matrix m
RV=np.array(m) #Row vector in matrix format
print('Row wise vector is:')
print(RV) #Displaying row vector


#For Column Vector
#Asking user to input number of Rows
R=int(input('Enter element of Vector:'))
M=[]
for i in range(R):
  for j in range(1):
    n=[]
    b=int(input('Enter elements of vector'))
    n.append(b)
  M.append(n)
CV= np.array(M)
print('Column wise vector is:')
print(CV)


##Question 2
#Creating a matrix of 5x5
#Input Method
Mat_Inp= []
for i in range(5): #Loop for Rows
  mat= []
  for j in range(5): #Loop for Columns
    #Asking user to input all the element of 5x5 matrix
    values= int(input('Enter the elements of Matrix:'))
    mat.append(values) #Adding all element into mat
  Mat_Inp.append(mat) #Adding all element of mat into a
#Displaying 5x5 Matrix
a=np.array(Mat_Inp)
print('The 5x5 matrix (By Input Metd.) is:')
print(a)

#Manual Method
#Taking manual input for 5x5 matrix
Manual_a=[[1,5,6,2,1],
          [5,8,9,2,0],
          [2,7,6,4,1],
          [8,3,0,7,4],
          [2,4,3,4,7]]
#Displaying the manual matrix
a= np.array(Manual_a)
print('The 5x5 matrix (Manually) is:')
print(a)






#Question 3
#Printing third row
print('Third Row of Matrix a is:')
print(a[2]) #Printing 3rd row(2 is taken for 3rd row because index starts with 0)

#Question 4
#Printing 4TH column
# for 4th column column will be constant but we have to print each elements of row so applied for loop to print all element of 4th column
print('Fourth Column of Matrix a is:')
for i in range(5):#Only row is changing so apply iteration for row
  print(a[i][3]) #Displaying the 4th column so fix the index of column (as index start from 0 so 3rd index means 4th column)

#Question 5
#Sorting Of Matrix
#Importing Numpy to do various operations
import numpy as np
print('Sorting of Matrix')
#Row wise
#Initialising sort matrix as 0
sort= [[0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0],
       [0,0,0,0,0]]

#Storing the sorted element in matrix sort
for i in range(5):
  for j in range(5):
    sort[i][j]= a[i][j]
#Row wise sorting
sort_RW=np.sort(sort,axis=1) #Numpy used to sort the matrix a
#Display of row wise sorted matrix
print('Row wise sorting is:')
print(sort_RW)
#Column wise sorting
sort_CW=np.sort(sort,axis=0) #Numpy used to sort the matrix a
#Displaying column wise sorted matrix
print('Column wise sorting is:')
print(sort_CW)


#Question 6
#Multiplication with 10 for the element greater than 2

#Initialising the value of b as 0
b=[[0,0,0,0,0],
   [0,0,0,0,0],
   [0,0,0,0,0],
   [0,0,0,0,0],
   [0,0,0,0,0]]
#Storing the value of a in b so that a is not disturbed and we can put resultant value in b
for i in range(5): #For iteration of rows
  for j in range(5): #For iteration of columns
    b[i][j]= a[i][j] #Storing all element of matrix a in b

#loop for rows
for i in range(5):
  for j in range(5): #For column
    if b[i][j] > 2:  #If condition to check the perticular element is greater than 2
      b[i][j]= b[i][j]*10 #Multiplying element which is greater than 2 with 10
    else:                 #Else condition works if element is not greater than 2
      b[i][j]=b[i][j] #If element is not greater than 2 then no change in element
#Displaying the matrix b
b= np.array(b) #Taking the value in matrix format by using numpy
print('Matrix b is:')
print(b) #Printing the matrix

#Question 7
#Addition of matrix a and b

#Result of sum is initialised as 0

Add=  [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0]]

#Loops are used for addition operation
for i in range(5): #For Rows iteration
    for j in range(5): #For Column iteration
        Add[i][j]=a[i][j]+b[i][j] #Element wise addition of matrix a and b

#Display of Resultant Matrix
Add=np.array(Add) #Taking the values in matrix formate by using numpy
print('Addition Of matrix a and b is:')
print(Add) #Displaying the resultant matrix

#Question 8

#Substration of Matrix b from a
#sub is initialise as 0
sub=[[0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0],
     [0,0,0,0,0]]

#Loop for substraction operation
for i in range(5): #for row iteration
  for j in range(5): #for column iteration
    sub[i][j]=a[i][j]-b[i][j] #Elementwise substracting matrix b from a
#Display of Resultant matrix
sub=np.array(sub) #Taking the values in matrix format by using numpy
print('Substraction of Matrix b from a is:')
print(sub) #Displaying the resultant matrix

#Question 9
#Multiplication Of Matrix
#Elementwise multiplication of matrix a and b
EWmult=[[0,0,0,0,0],
      [0,0,0,0,0],
      [0,0,0,0,0],
      [0,0,0,0,0],
      [0,0,0,0,0]]
#loop to multiply each elements
for i in range(5): #For rows iteration
  for j in range(5): #For column iteration
    EWmult[i][j]= a[i][j]*b[i][j] #Element wise multiplication operation
#Displaying resultant matrix after element wise multiplication
EWmult=np.array(EWmult) #Taking the values in matrix formate by using numpy
print('Element wise multiplication is:')
print(EWmult) #Displaying the result of element wise multiplication

#Matrix Multiplication



#Initialising the mult as 0
mult=  [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0]]
#To calculate the multiplication of two matrix
#Using Numpy calculating multiplication of two matrix
mult = np.dot(a,b)
#Displaying the result of multiplication
print('Matrix Multiplication')
for r in mult:
    print(r)

#Question 10
#Divison of elements of matrix a by 18
#Initialisation of div_a as 0 to store the resultant value
div_a= [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0]]

#loop to divide every elements of matrix a by 18
for i in range(5): #For row iteration
  for j in range(5): #For Column iteration
    div_a[i][j]= a[i][j]/18 #Dividing each element by 18
#Displaying the resultant Matrix
div_a=np.array(div_a)
print('Division Of Matrix a is:')
print(div_a)

#Divison of elements of matrix b by 18
print('Division of matrix (b) with 18 is:')
#Initialisation of div_b as 0 to store the resultant value
div_b= [[0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0],
        [0,0,0,0,0]]

#loop to divide every elements of matrix b by 18
for i in range(5): #for iterating rows
  for j in range(5):#for iterating columns
    div_b[i][j]= b[i][j]/18 #Dividing each element of b with 18
#Displaying the resultant Matrix
div_b=np.array(div_b) #Taking value in matrix form by using numpy
print('Division of matrix b is:')
print(div_b)

#Question 11
#Inverse of Matrix a
print('Inverse of (a) is:')
print(np.linalg.inv(a)) #Determining inverse by using numpy
#Inverse of Matrix b
print('Inverse of (b) is:')
print(np.linalg.inv(b)) #Determining inverse of b by using numpy

#Rank of Matrix a
print('Rank of matrix (a) is:')
print(np.linalg.matrix_rank(a))#Numpy is used to determine the rank of matrix a
#Rank of Matrix b
print('Rank of matrix (b) is:')
print(np.linalg.matrix_rank(b))#Numpy is used to determine the rank of matrix b

#Condition Number of matrix (a)
print('Condition Number (a) is:')
print(np.linalg.cond(a)) #Numpy is used to determine the rank of matrix a
#Condition Number of matrix b
print('Condition Number (b) is:')
print(np.linalg.cond(b)) #Numpy is used to determine the rank of matrix b

#Singular Value Decomposition(SVD) of matrix a and b
u_a,s_a,v_a= np.linalg.svd(a)
u_b,s_b,v_b= np.linalg.svd(b)
print('SVD of matrix a is:',u_a,s_a,v_a)
print('SVD of matrix b is:',u_b,s_b,v_b)



#Norm of Matrix a
print('Norm of matrix (a) is:')
print(np.linalg.norm(a)) #Norm of matrix a is determined by using numpy
#Norm of Matrix b
print('Norm of matrix (b) is:')
print(np.linalg.norm(b)) #Norm of matrix b is determined by using numpy


#Question 12
#Norm of column vector
print('Norm of column vector (CV):')
print(np.linalg.norm(CV))
#Inner product
print('Inner Product')
print(np.dot(CV.T,CV))
#Outer Product
print('Outer Product:')
print(np.outer(CV,CV))






#Question 13

#Defining a derivative function
#Initialise the default value of h and method
def derivative(f,a,h=0.01,method='central'):
  #Computing different formula to determine derivative at step size h and at value a
#Parameters:
#f=function
#a=Number on which derivative have to calculate (x=a)
#method=String for checking forward,backward,central
#h= Step size

#Returns:
#Different formulas:
#forward=(f(a+h)-f(a))/h
#backward: (f(a)-f(a-h))/h
#central: (f(a+h)-f(a-h))/(2*h)
  #Comparing the method either it is forward,Backward or Central
  if method == 'forward':
    return(f(a+h)- f(a))/h
  elif method== 'backward':
    return(f(a)-f(a-h))/h
  elif method== 'central':
    return(f(a+h)-f(a-h))/(2*h)

print('Derivative of (e^x) is:')
#Derivative of exponential function
der_exp=derivative(np.exp,0.5) #Calling derivative function for exp
print(der_exp) #Printing the value of derivative
print('Derivative of (cos) is:')
#Derivative of cos function
der_cos=derivative(np.cos,0.5) #Calling derivative function for cos
print(der_cos) #Printing the value of derivative




















Manual Input:
Row Vector:
[[1 2 3]]
Column Vector:
[[1]
 [2]
 [3]]
Input Method:
Row Vector:
Enter number of column:3
Enter elements of Vector:1
Enter elements of Vector:2
Enter elements of Vector:3
Row wise vector is:
[1 2 3]
Enter element of Vector:3
Enter elements of vector5
Enter elements of vector6
Enter elements of vector8
Column wise vector is:
[[5]
 [6]
 [8]]
Enter the elements of Matrix:6
Enter the elements of Matrix:8
Enter the elements of Matrix:9
Enter the elements of Matrix:7
Enter the elements of Matrix:5
Enter the elements of Matrix:1
Enter the elements of Matrix:0
Enter the elements of Matrix:2
Enter the elements of Matrix:6
Enter the elements of Matrix:9
Enter the elements of Matrix:7
Enter the elements of Matrix:1
Enter the elements of Matrix:4
Enter the elements of Matrix:3
Enter the elements of Matrix:2
Enter the elements of Matrix:5
Enter the elements of Matrix:0
Enter the elements of Matrix:7
Enter the elements of Matrix:6
Enter the elements of Matrix:1
Enter the 

In [ ]:
#Question 14
#Importing pandas library
import pandas as pd
path= "/content/drive/MyDrive/Dataset/AWS.csv" #Storing the path of .csv file in variable path
d= pd.read_csv(path) #Reading the .csv file
d.head(10) #Displaying the first 10 rows of .csv file



<ipython-input-6-d2946fef2c1a>:3: DtypeWarning: Columns (36,43,44,45,46,50,58) have mixed types. Specify dtype option on import or set low_memory=False.
  d= pd.read_csv(path)


STATION                 DATE  SOURCE  LATITUDE  LONGITUDE  ELEVATION  \
0  74486094789  2021-01-01T00:00:00       4  40.63915   -73.7639        2.7   
1  74486094789  2021-01-01T00:51:00       7  40.63915   -73.7639        2.7   
2  74486094789  2021-01-01T01:51:00       7  40.63915   -73.7639        2.7   
3  74486094789  2021-01-01T02:51:00       7  40.63915   -73.7639        2.7   
4  74486094789  2021-01-01T03:00:00       4  40.63915   -73.7639        2.7   
5  74486094789  2021-01-01T03:51:00       7  40.63915   -73.7639        2.7   
6  74486094789  2021-01-01T04:51:00       7  40.63915   -73.7639        2.7   
7  74486094789  2021-01-01T04:59:00       6  40.63915   -73.7639        2.7   
8  74486094789  2021-01-01T04:59:00       6  40.63915   -73.7639        2.7   
9  74486094789  2021-01-01T05:51:00       7  40.63915   -73.7639        2.7   

                               NAME REPORT_TYPE CALL_SIGN QUALITY_CONTROL  \
0  JFK INTERNATIONAL AIRPORT, NY US       FM-12     99999            V020   
1  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   
2  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   
3  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   
4  JFK INTERNATIONAL AIRPORT, NY US       FM-12     99999            V020   
5  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   
6  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   
7  JFK INTERNATIONAL AIRPORT, NY US       SOD       KJFK             V030   
8  JFK INTERNATIONAL AIRPORT, NY US       SOM       KJFK             V030   
9  JFK INTERNATIONAL AIRPORT, NY US       FM-15     KJFK             V030   

   ...  OC1  OD1                    OE1                    OE2  \
0  ...  NaN  NaN                    NaN                    NaN   
1  ...  NaN  NaN                    NaN                    NaN   
2  ...  NaN  NaN                    NaN                    NaN   
3  ...  NaN  NaN                    NaN                    NaN   
4  ...  NaN  NaN                    NaN                    NaN   
5  ...  NaN  NaN                    NaN                    NaN   
6  ...  NaN  NaN                    NaN                    NaN   
7  ...  NaN  NaN  1,24,01028,320,9999,5  2,24,00939,330,9999,5   
8  ...  NaN  NaN                    NaN                    NaN   
9  ...  NaN  NaN                    NaN                    NaN   

                     OE3            RH1            RH2            RH3  \
0                    NaN            NaN            NaN            NaN   
1                    NaN            NaN            NaN            NaN   
2                    NaN            NaN            NaN            NaN   
3                    NaN            NaN            NaN            NaN   
4                    NaN            NaN            NaN            NaN   
5                    NaN            NaN            NaN            NaN   
6                    NaN            NaN            NaN            NaN   
7  3,24,00496,999,9999,5  024,X,093,D,4  024,N,055,D,4  024,M,073,D,4   
8                    NaN            NaN            NaN            NaN   
9                    NaN            NaN            NaN            NaN   

                                                 REM  \
0  SYN08074486 32566 83212 10050 21028 30249 4026...   
1  MET10612/31/20 19:51:03 METAR KJFK 010051Z 320...   
2  MET10612/31/20 20:51:03 METAR KJFK 010151Z 350...   
3  MET11212/31/20 21:51:03 METAR KJFK 010251Z 340...   
4  SYN06474486 32966 23407 10022 21044 30276 4028...   
5  MET10612/31/20 22:51:03 METAR KJFK 010351Z 340...   
6  MET11612/31/20 23:51:03 METAR KJFK 010451Z 350...   
7  SOD75624 HR PRECIPITATION (IN): 0.36 SNOW DEPT...   
8  SOM792PCP MTOT:2.66 PCP GT 24HRS:1.23 DATE(S):...   
9  MET12401/01/21 00:51:02 METAR KJFK 010551Z 350...   

                                                 EQD  
0                                                NaN  
1                              